spring:
  datasource:
    username: XXXX
    password: XXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://XXXXXXXXXXX:XXXXX/XXXXX?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai

